namespace:
  create: false
  name: spend-control
gateway:
  enabled: true
  className: kgateway
  name: spend-control-gateway
  listener:
    port: 80
    protocol: HTTP
  tls:
    enabled: false
    port: 443
    protocol: HTTPS
    mode: Terminate
    certificateSecretName: spend-control-gateway-origin-tls
serviceAccount:
  create: false
  name: spend-control-workload
config:
  create: false
  existingConfigMapName: spend-control-config
imagePullSecrets: []
rollout:
  revision: ""
env:
  appEnv: production
  backendCorsOrigins: https://fin.nexaflow.site,https://myfinagent.online,https://www.myfinagent.online
  financeDefaultCurrency: INR
azure:
  tenantId: "23009888-f985-4438-a6a8-32650f036be3"
  managedIdentityClientId: "c8ec5bbe-a9ef-4593-ac8f-4e8269fd327c"
  aiFoundryEndpoint: "https://spendpilotprodai2300.cognitiveservices.azure.com/"
  aiProjectEndpoint: ""
  aiModelDeployment: "gpt-4-1-mini"
  documentIntelligenceEndpoint: "https://spendpilotproddoc2300.cognitiveservices.azure.com/"
  storageAccountUrl: "https://sp2300proddocs.blob.core.windows.net/"
  storageContainerName: expense-documents
keyVault:
  enabled: true
  name: spendpilot-prod-kv-2300
  secretProviderClassName: spend-control-secrets-provider
  mountPath: /mnt/secrets-store
  databaseUrlSecretName: spend-control-database-url
  devAuthSecretSecretName: spend-control-dev-auth-secret
frontend:
  image:
    repository: spendpilotglobalacr.azurecr.io/spend-control-frontend
    tag: 8943dc2
    digest: "sha256:6815b3bc7dbbddc00507d68b663a68b8e0968e85d4f31627841a7861ef60c3c9"
    pullPolicy: IfNotPresent
  replicaCount: 2
  nextPublicApiBaseUrl: /api
identityService:
  image:
    repository: spendpilotglobalacr.azurecr.io/spend-control-identity
    tag: "v1.0.0"
    digest: "sha256:150b2083b0e09ce745c7ab66f4f862200f650c16454fa1b0b91cfa44af6e09cb"
    pullPolicy: IfNotPresent
  replicaCount: 2
financeService:
  image:
    repository: spendpilotglobalacr.azurecr.io/spend-control-finance
    tag: "a3b497b"
    digest: ""
    pullPolicy: IfNotPresent
  replicaCount: 2
documentsService:
  image:
    repository: spendpilotglobalacr.azurecr.io/spend-control-documents
    tag: "a3b497b"
    digest: ""
    pullPolicy: IfNotPresent
  replicaCount: 2
migrationJob:
  enabled: true
  image:
    repository: spendpilotglobalacr.azurecr.io/spend-control-identity
    tag: "v1.0.0"
    digest: "sha256:150b2083b0e09ce745c7ab66f4f862200f650c16454fa1b0b91cfa44af6e09cb"
    pullPolicy: IfNotPresent
secrets:
  create: false
  existingSecretName: spend-control-secrets
auth:
  mode: entra
  authority: https://login.microsoftonline.com/common
  frontendClientId: "60a50899-f5cb-4a91-bce6-3e5df72d8b79"
  backendClientId: "4863701b-0a8d-4645-922f-1e8adebff2b2"
  backendAudience: "api://spendpilot-prod-backend-api-2300"
  apiScope: "api://spendpilot-prod-backend-api-2300/access_as_user"
  allowedTenantIds: ""
  platformAdminEmails: ""
