env:
  appEnv: staging
  backendCorsOrigins: https://staging.example.z01.azurefd.net
auth:
  mode: entra
  authority: https://login.microsoftonline.com/common
frontend:
  image:
    repository: spendpilotglobalacr.azurecr.io/spend-control-frontend
    tag: 8943dc2
    digest: "sha256:6815b3bc7dbbddc00507d68b663a68b8e0968e85d4f31627841a7861ef60c3c9"
  replicaCount: 2
identityService:
  image:
    repository: spendpilotglobalacr.azurecr.io/spend-control-identity
    tag: 7faf974
    digest: "sha256:57068e0784b3b0fd7a74220cddb0b411c4dbff2a02100d3c0750af9b9d6984ef"
  replicaCount: 2
financeService:
  image:
    repository: spendpilotglobalacr.azurecr.io/spend-control-finance
    tag: staging-candidate
    digest: ""
  replicaCount: 2
documentsService:
  image:
    repository: spendpilotglobalacr.azurecr.io/spend-control-documents
    tag: 961704e
    digest: "sha256:2aa4f42e66ed1e1f420b69f5abd3f1ea6dc46abb61f2211e3d9d09722608fde5"
  replicaCount: 2
migrationJob:
  image:
    repository: spendpilotglobalacr.azurecr.io/spend-control-identity
    tag: 7faf974
    digest: "sha256:57068e0784b3b0fd7a74220cddb0b411c4dbff2a02100d3c0750af9b9d6984ef"
