env:
  appEnv: staging
  backendCorsOrigins: https://staging.example.z01.azurefd.net
auth:
  mode: entra
  authority: https://login.microsoftonline.com/common
frontend:
  image:
    repository: spendpilotglobalacr.azurecr.io/spend-control-frontend
    tag: 8943dc2
    digest: "sha256:6815b3bc7dbbddc00507d68b663a68b8e0968e85d4f31627841a7861ef60c3c9"
  replicaCount: 2
identityService:
  image:
    repository: spendpilotglobalacr.azurecr.io/spend-control-identity
    tag: 7faf974
    digest: "sha256:57068e0784b3b0fd7a74220cddb0b411c4dbff2a02100d3c0750af9b9d6984ef"
  replicaCount: 2
financeService:
  image:
    repository: spendpilotglobalacr.azurecr.io/spend-control-finance
    tag: 961704e
    digest: "sha256:ace921d17e7d9262f905649ef07f5e14115868dd526201b96d524c39829fc126"
  replicaCount: 2
documentsService:
  image:
    repository: spendpilotglobalacr.azurecr.io/spend-control-documents
    tag: 7faf974
    digest: "sha256:60b2bca3fa458c00279dfbbdb0bee2f48ad23e0ff48481529071664838bc1d39"
  replicaCount: 2
migrationJob:
  image:
    repository: spendpilotglobalacr.azurecr.io/spend-control-identity
    tag: 7faf974
    digest: "sha256:57068e0784b3b0fd7a74220cddb0b411c4dbff2a02100d3c0750af9b9d6984ef"
